version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: files_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./packages/backend:/app/packages/backend
      - /app/packages/backend/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/files_db
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
volumes:
  pgdata:
  frontend_node_modules: